var annotated =
[
    [ "AnyObject", "classAnyObject.html", "classAnyObject" ],
    [ "Building", "classBuilding.html", "classBuilding" ],
    [ "Creature", "classCreature.html", "classCreature" ],
    [ "CreatureTest", "classCreatureTest.html", null ],
    [ "DecisionMaker", "classDecisionMaker.html", "classDecisionMaker" ],
    [ "God", "classGod.html", "classGod" ],
    [ "Humanoid", "classHumanoid.html", "classHumanoid" ],
    [ "Indexator", "classIndexator.html", "classIndexator" ],
    [ "IWorld", "classIWorld.html", "classIWorld" ],
    [ "NonHumanoid", "classNonHumanoid.html", "classNonHumanoid" ],
    [ "Object", "classObject.html", "classObject" ],
    [ "ObjectFactory", "classObjectFactory.html", "classObjectFactory" ],
    [ "ObjectHeap", "classObjectHeap.html", "classObjectHeap" ],
    [ "PendingAction", "classPendingAction.html", "classPendingAction" ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "Resource", "classResource.html", "classResource" ],
    [ "Shape", "classShape.html", "classShape" ],
    [ "Tool", "classTool.html", "classTool" ],
    [ "ViewObject", "classViewObject.html", "classViewObject" ],
    [ "VisualState", "classVisualState.html", "classVisualState" ],
    [ "Weather", "classWeather.html", "classWeather" ],
    [ "World", "classWorld.html", "classWorld" ]
];